list: $/roojai/blogs/models/blog/columns.yaml
modelClass: Roojai\Blogs\Models\Blog
title: Blogs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'roojai/blogs/blogs/update/:id'
